sudo: false

language: scala

scala:
  - 2.12.7
  - 2.11.12

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/

env:
  - JOB=Test

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport

before_install:
  - git fetch --tags

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

after_success:
  - bash <(curl -s https://codecov.io/bash)

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork


jobs:
  include:
    - env: JOB=Documentation
      scala:
        - 2.12.7
      before_install:
        - export PATH=${PATH}:./vendor/bundle
      install:
        - rvm use 2.4 --install --fuzzy
        - gem update --system
        - gem install sass
        - gem install jekyll -v 3.2.1
      script:
        - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash scripts/publishMicrosite.sh; fi
        - if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then echo "Not in master branch, skipping deploy and release"; fi
      after_success: ignore
    - stage: release
      env: JOB=Release
      script: sbt ci-release
