language: scala
scala:
  - 2.12.7
  - 2.11.12
jdk:
  - oraclejdk8
env:
  - JOB=Test-$TRAVIS_SCALA_VERSION

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - env: JOB=Documentation
      scala:
        - 2.12.7
      jdk: oraclejdk8
      before_install:
        - export PATH=${PATH}:./vendor/bundle
      install:
        - rvm use 2.2.8 --install --fuzzy
        - gem update --system
        - gem install sass
        - gem install jekyll -v 3.2.1
      script:
        - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash scripts/publishMicrosite.sh; fi
        - if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then echo "Not in master branch, skipping deploy and release"; fi
      after_success: ignore
