name: Test Charged
baseurl: /test-charged
description: Supercharge your testing
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.7+4-240d87a0-SNAPSHOT
org: docs
markdown: kramdown
