name: Test Charged
baseurl: /test-charged
description: Supercharge your testing
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.7+3-f84a0027-SNAPSHOT
org: docs
markdown: kramdown
