name: Test Charged
baseurl: /test-charged
description: Supercharge your testing
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.11+7-69f2d40c-SNAPSHOT
org: com.github.fulrich
markdown: kramdown
