name: Test Charged
baseurl: /test-charged
description: Supercharge your testing
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.10+2-c0af69dd-SNAPSHOT
org: com.github.fulrich
markdown: kramdown
