name: Test Charged
baseurl: /test-charged
description: Supercharge your testing
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.13+1-a4226b99-SNAPSHOT
org: com.github.fulrich
markdown: kramdown
