name: Test Charged
baseurl: /test-charged
description: Supercharge your testing
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.12+1-51b37c82-SNAPSHOT
org: com.github.fulrich
markdown: kramdown
