name: Test Charged
baseurl: /test-charged
description: Supercharge your testing
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.11+3-dcc25c92-SNAPSHOT
org: com.github.fulrich
markdown: kramdown
