name: Test Charged
baseurl: /test-charged
description: Supercharge your testing
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.15+1-19121596-SNAPSHOT
org: com.github.fulrich
markdown: kramdown
