name: Test Charged
baseurl: /test-charged
description: Supercharge your testing
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.5+6-8aed9f3e-SNAPSHOT
org: docs
markdown: kramdown
