name: Test Charged
baseurl: /test-charged
description: Supercharge your testing
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.9+2-d014321b-SNAPSHOT
org: com.github.fulrich
markdown: kramdown
