version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    working_directory: ~/test-charged

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.sbt" }}
        - v1-dependencies-

    - run:
        name: Compile
        command: cat /dev/null | sbt +test:compile

    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies--{{ checksum "build.sbt" }}

    - run:
        name: Test
        command: cat /dev/null | sbt +test:test

    - store_test_results:
        path: target/test-reports

    - run:
        name: Publish Signed
        command: sbt +publishSigned
